# Generated by Django 4.2.2 on 2023-06-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
